import os
import json
from google.oauth2 import service_account
from googleapiclient.discovery import build

GOOGLE_CREDS = os.environ.get("GOOGLE_CREDENTIALS")
CACHE_FILE = "indexed_jobs.json"

def load_persistent_cache():
    """Loads the history of sent jobs from the repo."""
    if os.path.exists(CACHE_FILE):
        try:
            with open(CACHE_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            print(f"⚠️ Cache read error: {e}")
            return []
    return []

def save_persistent_cache(cache_list):
    """Saves the updated history back to the file."""
    with open(CACHE_FILE, "w", encoding="utf-8") as f:
        json.dump(cache_list, f, indent=2)

def main():
    if not os.path.exists("pending_urls.txt"):
        print("ℹ️ No new job pages were generated.")
        return

    if not GOOGLE_CREDS:
        print("❌ Error: GOOGLE_CREDENTIALS secret is missing.")
        return

    # 1. Load the history (what we've sent in the past)
    history = load_persistent_cache()
    
    # 2. Setup Google API
    info = json.loads(GOOGLE_CREDS)
    creds = service_account.Credentials.from_service_account_info(info, scopes=["https://www.googleapis.com/auth/indexing"])
    service = build("indexing", "v3", credentials=creds)

    # 3. Read current batch from the text file generated by content_manager.py
    with open("pending_urls.txt", "r") as f:
        current_batch = [line.strip() for line in f if line.strip()]

    newly_sent_count = 0

    for url in current_batch:
        # Check if this URL is already in our history
        if url in history:
            print(f"⚡ Skipping: {url} (Already in cache/sent previously)")
            continue

        try:
            # Send to Google
            service.urlNotifications().publish(body={"url": url, "type": "URL_UPDATED"}).execute()
            print(f"🚀 Google Indexed: {url}")
            
            # Add to history so we never send it again
            history.append(url)
            newly_sent_count += 1
        except Exception as e:
            print(f"❌ Error sending {url}: {e}")

    # 4. Save the updated history back to indexed_jobs.json
    if newly_sent_count > 0:
        save_persistent_cache(history)
        print(f"✅ Cache updated with {newly_sent_count} new entries.")
    else:
        print("ℹ️ No new indexing requests were necessary.")

if __name__ == "__main__":
    main()
